# ----- Builder Stage -----
FROM golang:1.24 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Install gqlgen and tidy modules
RUN go mod tidy
RUN go install github.com/99designs/gqlgen@latest

# Build users service from /app/services/users
WORKDIR /app/services/orders
RUN GOOS=linux GOARCH=amd64 go build -o main .

# ----- Runtime Stage -----
FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/main /main
RUN chmod +x /main

# Set the correct port (adjust for each service)
EXPOSE 4003

# Run the service
ENTRYPOINT ["/main"]