FROM --platform=$BUILDPLATFORM golang:1.24-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

RUN apk add --no-cache git

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy all source code
COPY . .

# Build with explicit target platform
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o server ./services/orders && chmod +x server

FROM --platform=$TARGETPLATFORM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/server .

COPY --from=builder /app/.env* ./

EXPOSE 4003

CMD ["./server"]