// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"github.com/tagaertner/e-commerce-graphql/services/orders/models"
)

type Query struct {
}

type User struct {
	ID     string          `json:"id"`
	Orders []*models.Order `json:"orders,omitempty"`
}

func (User) IsEntity() {}
