// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Order struct {
	ID         string  `json:"id"`
	UserID     string  `json:"userId"`
	ProductID  string  `json:"productId"`
	Quantity   int     `json:"quantity"`
	TotalPrice float64 `json:"totalPrice"`
	Status     string  `json:"status"`
	CreatedAt  string  `json:"createdAt"`
}

type Query struct {
}
