package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"github.com/tagaertner/job-stories/services/stories/generated"
)

// FindJobStoryByID is the resolver for the findJobStoryByID field.
func (r *entityResolver) FindJobStoryByID(ctx context.Context, id string) (*generated.JobStory, error) {
	story, err := r.StoryService.GetStoryByID(id)
	if err != nil {
		return nil, err
	}
	return ToGraphQLStory(story), nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
