// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Entity interface {
	IsEntity()
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description *string `json:"description,omitempty"`
	Inventory   int     `json:"inventory"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Service struct {
	Sdl *string `json:"sdl,omitempty"`
}
