// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description *string `json:"description,omitempty"`
	Inventory   int     `json:"inventory"`
}

type Query struct {
}
