# syntax=docker/dockerfile:1.4

FROM --platform=$BUILDPLATFORM golang:1.24-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o server ./services/products && chmod +x server

FROM --platform=$TARGETPLATFORM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/server .

COPY --from=builder /app/.env* ./

EXPOSE 4101

CMD ["./server"]