// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Query struct {
}

type User struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Role   string `json:"role"`
	Active bool   `json:"active"`
}

func (User) IsEntity() {}
