// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type DeleteUserInput struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	Name   *string `json:"name,omitempty"`
	Email  *string `json:"email,omitempty"`
	Role   *string `json:"role,omitempty"`
	Active *bool   `json:"active,omitempty"`
}
