package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"e-commerce/services/users/generated"
	"fmt"
)

// Users is the resolver for the users field.
// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*generated.User, error) {
	return r.UserService.GetAllUsers(), nil
}

func (r *queryResolver) User(ctx context.Context, id string) (*generated.User, error) {
	user := r.UserService.GetUserByID(id)
	if user == nil {
		return nil, fmt.Errorf("user with id %s not found", id)
	}
	return user, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
