// resolvers/user_mapper.go
package resolvers

import (
  "github.com/tagaertner/e-commerce-graphql/services/users/generated"
  "github.com/tagaertner/e-commerce-graphql/services/users/models"
)

// Maps a GORM User (DB) to a GraphQL User (generated by gqlgen)
func ToGraphQLUser(u *models.User) *generated.User {
  return &generated.User{
    ID:     u.ID,
    Name:   u.Name,
    Email:  u.Email,
    Role:   u.Role,
    Active: u.Active,
  }
}