# ---- Builder Stage ----
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go mod tidy
RUN go install github.com/99designs/gqlgen@latest

# Build users service from /app/services/users
WORKDIR /app/services/users
RUN GOOS=linux GOARCH=amd64 go build -o /app/main .

# ---- Runtime Stage ----
FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/main /main
RUN chmod +x /main

EXPOSE 4002
ENTRYPOINT ["/main"]