package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"e-commerce/services/products/generated"
	"fmt"
)

// FindProductByID is the resolver for federation entity Product
func (r *entityResolver) FindProductByID(ctx context.Context, id string) (*generated.Product, error) {
	product := r.ProductService.GetProductByID(id)
	if product == nil {
		return nil, fmt.Errorf("product not found")
	}
	return product, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
