package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	generated1 "github.com/tagaertner/e-commerce-graphql/services/products/generated"
	models1 "github.com/tagaertner/e-commerce-graphql/services/products/models"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*models1.Product, error) {
	return r.ProductService.GetAllProducts()
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*models1.Product, error) {
	return r.ProductService.GetProductByID(id)
}

// Query returns generated1.QueryResolver implementation.
func (r *Resolver) Query() generated1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
