package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"e-commerce/services/products/generated"
	"fmt"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*generated.Product, error) {
	return r.ProductService.GetAllProducts(), nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*generated.Product, error) {
	product := r.ProductService.GetProductByID(id)
	if product == nil {
		return nil, fmt.Errorf("product not found")
	}
	return product, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
